#!/usr/bin/env python3

import glob
import sys
import numpy as np
from mpi4py import MPI
import numpy
import sys
import os

# Out folder
survey = 'North_Flinders_survey'
level = 'level_0'
outdata = '/g/data/<xy12>/<abc123>/AusLAMP/South_Australia/' + survey + '/' + level
product = 'Concatenated_Time_Series_ASCII_per_run'
merged_survey = outdata + '/' + product
# merged_maralinga = '/g/data/<xy12>/my80_test_full/used_scripts/MT_L0_ASCII/L0_onefileperrun/02_workspace/merged_data_maralinga'

# Folder where the logs are kept
log_dir = '/g/data/<xy12>/<abc123>/supplementing_files/' + survey

log_fileperrun = log_dir + "/list_fileperrun.log"

try:
    os.makedirs(merged_survey)
except:
    # directory already exists
    pass

def mpi_log_print(out, pre=0, msg='empty message', file= sys.stdout, flush=True):
    if out:
        print('\t'*pre + msg, file= file, flush=flush)
class merge_ascii:
    """
    """
    def __init__(self, fnm, lognm = '', exclude_sta = set() ):
        """
        fnm: Filename of the *.log generated by `wc -l *` that is described in README.
        exclude_sta: stations to be excluded.
        """
        self.comm = MPI.COMM_WORLD
        self.mpi_size = self.comm.Get_size()
        self.rank     = self.comm.Get_rank()
        self.mpi_log = open('%s_%03d.log' % (lognm, self.rank), 'w' )
        #
        self.fnm = fnm
        self.exclude_sta = exclude_sta
        #
        self.vol = dict()
        self.rd()
        self.prepare_mpi_job()

    def rd(self):
        """
        Read data and organize data.
        """
        mpi_log_print(True, 0, '# Input data from %s ...' % self.fnm, file=self.mpi_log, flush=True )
        mpi_log_print(True, 1, 'ignore stations: %s' % (', '.join(list(self.exclude_sta))) , file=self.mpi_log, flush=True )
        for line in open(self.fnm):
            n_sample, data_fnm = line.strip().split()
            n_sample = int(n_sample)
            sta, day, tmp = data_fnm.split('/')[-3:]
            if sta in self.exclude_sta:
                continue # get rid of excluded stations
            dat, com = tmp.split('.')
            if sta not in self.vol:
                self.vol[sta] = dict()
            if com not in self.vol[sta]:
                self.vol[sta][com] = dict()
            self.vol[sta][com][day] = {'size': n_sample, 'nm': dat}
            self.rootdir = '/'+'/'.join( open(self.fnm).readline().split()[1].split('/')[:-3] ) + '/'
    def get_path(self, com, sta, day):
        try:
            path = '/'.join( [self.rootdir, sta, day, self.vol[sta][com][day]['nm']] ) +'.'+com
            return path
        except:
            mpi_log_print(True, 0, 'Err: cannot find path for file %s %s %s' % (com, sta, day), file=sys.stderr, flush=True )
    def prepare_mpi_job(self):
        """
        """
        nsta = len( self.vol.keys() )
        chunk = int(np.ceil(nsta/self.mpi_size) )
        i_start, i_end = chunk*self.rank, chunk*(self.rank+1)
        if i_end > nsta:
            i_end = nsta
        sta_lst = sorted(list(self.vol.keys() ) )
        self.proc_sta = sta_lst[i_start: i_end]
        mpi_log_print(True, 0, '# Init mpi job. This node takes care of stations: [%d->%d) (%d/%d)' % (i_start, i_end, len(self.proc_sta ), nsta) , file=self.mpi_log, flush=False)
        mpi_log_print(True, 1, '%s' % ', '.join(self.proc_sta) , file=self.mpi_log, flush=True)

    def merge(self, out_prename, cut_head=1, cut_end=1):
        """
        Merge station by station
        cut_head, cut_end (1, 1) : how many days to remove when merging
        """
        mpi_log_print(True, 0, '# Merging, get rid of starting and end days (%d, %d)...' % (cut_head, cut_end), file=self.mpi_log, flush=True)
        nsta = len(self.proc_sta)
        for ista, sta in enumerate(self.proc_sta):
            for com in self.vol[sta]:
                day_lst = sorted(list(self.vol[sta][com].keys() ) )
                n_days = len(day_lst)

                outfnm = '%s/%s/%s-%s_%s.%s' % (out_prename, sta, sta, day_lst[cut_head], day_lst[cut_end*-1-1], com)
                os.makedirs('%s/%s' % (out_prename, sta), exist_ok=True)  # Ensure station folder exists

                # outfnm = '%s/%s-%s_%s.%s' % (out_prename, sta, day_lst[cut_head], day_lst[cut_end*-1-1], com)

                mpi_log_print(True, 1, '(%d/%d) %s %s ==> %s' % (ista+1, nsta, sta, com, outfnm), file=self.mpi_log, flush=True )
                fp = open(outfnm, 'w')
                for a_day in day_lst[cut_head: n_days-cut_end]:
                    path = self.get_path(com, sta, a_day)
                    mpi_log_print(True, 2, '%s' % path, file=self.mpi_log, flush=True )
                    vol_in = open(path, 'r').readlines()
                    print(''.join(vol_in), end='', file= fp)
                fp.close()





# Add all sites here that 01_check finds to be good. Exclude the station you are working on
if __name__ == "__main__":
#    sta_exclude_set = set( (
#       'SA205','SA206','SA206_2','S207A','SA208','SA208_2','SA209','SA210A','SA210B','SA211', 
#       'SA213','SA214','SA215','SA216','SA217','SA218_2','SA219_2','SA220','SA221','SA222', 
#       'SA225','SA228','SA229','SA229_2A','SA229_2B','SA231','SA232','SA234','SA235','SA237', 
#       'SA238','SA239','SA240_2','SA241','SA241_2A','SA241_2B','SA253','SA254','SA255','SA256', 
#       'SA257','SA258','SA259','SA260_2A','SA260_2B','SA261','SA262','SA262_2','SA263','SA278', 
#       'SA279','SA280','SA281','SA282','SA283','SA284','SA285_2A','SA285_2B','SA286','SA287', 
#       'SA288','SA289','SA292','SA293','SA303','SA304','SA305','SA306','SA307','SA308', 
#       'SA308A','SA308B','SA309','SA310A','SA310B','SA311','SA312','SA313','SA314','SA315', 
#       'SA316','SA317','SA328','SA329','SA329A','SA330','SA330A','SA332A','SA333','SA333_2A', 
#       'SA333_2B','SA334','SA336','SA337','SA340','SA341','SA342','SA354','SA355A','SA355B' 
#        # Done: 
#        
#    ) )


    sta_exclude_set = set( (
        'NF01','NF02','NF02_2','NF05_2','NF08','NF09','NF10','NF11','NF16','NF17','NF18_2',
        'NF20','NF21','NF22','NF24','NF25','NF26','NF27','NF28','NF29','NF30','NF31','NF32',  
        'NF34','NF35','NF36','NF38','NF39','NF40','NF43','NF44','NF45','NF46','NF46_2A','NF47',### Good stations
        'NF03','NF04','NF05','NF06','NF07','NF12','NF13','NF13_2','NF14','NF15',
        'NF18','NF19','NF23','NF33','NF37','NF41','NF41_2','NF42','NF46_2B'
    
        # Done: NF03 NF04 NF05 NF06 NF07 NF12 NF13 NF13_2 NF14 NF15 NF18 NF19 NF23 NF33 NF37 NF41 NF41_2 NF42 NF46_2B
    ) )

    ######### Merge ASCII
    app = merge_ascii(log_fileperrun, log_dir + '/survey_merge_', sta_exclude_set)
    app.merge(merged_survey, 15, 0)

    

